controller_frequency: 50.0
recovery_behaviour_enabled: true
		
TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.25
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.5
  acc_lim_theta: 0.7
  acc_lim_x: 1.0
  acc_lim_y: 1.0
  escape_vel: -0.25

  holonomic_robot: true
  y_vels: [-0.5, -0.25, 0.25, 0.5]
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.1
  goal_distance_bias: 0.8
  path_distance_bias: 0.6
  sim_time: 1.5
  heading_lookahead: 1.0
  oscillation_reset_dist: 0.25

  vx_samples: 6
  vtheta_samples: 20
  dwa: false

