obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.61, 0.575], [-0.61, 0.575], [-0.61, -0.815], [0.61, -0.815]]
#footprint: [1,2,3,4]
# 1 4
# 2 3
inflation_radius: 0.25
observation_sources: front_scan kinect #rear_scan 
front_scan: {topic: scan, sensor_frame: front_laser, observation_persistence: 0.0, expected_update_rate: 0.1, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 2.5, raytrace_range: 3.0, inf_is_valid: false}
kinect: {topic: kinect_scan, sensor_frame: "", observation_persistence: 0.0, expected_update_rate: 0.0, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 2.5, raytrace_range: 3.0, inf_is_valid: false}
#rear_scan: {topic: scan, sensor_frame: rear_laser, observation_persistence: 0.0, expected_update_rate: 0.1, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 2.5, raytrace_range: 3.0, inf_is_valid: false}


