DWAPlannerROS: 
  #Robot config parameters
  acc_lim_th: 2.5
  acc_lim_x: 1.7
  acc_lim_y: 1.7
  max_vel_x: 0.5 
  min_vel_x: -0.5
  max_vel_y: 0.5 
  min_vel_y: -0.5 
  max_trans_vel: 0.5
  min_trans_vel: 0.1
  max_rot_vel: 1.0 
  min_rot_vel: 0.2

  #Goal tolerance parameters
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05 
  latch_xy_goal_tolerance: false

  #forward simulation parameters
  sim_time: 1.7 
  sim_granularity: 0.025 
  vx_samples: 10 
  vy_samples: 10 
  vtheta_samples: 20 
  controller_frequency: 20.0
  penalize_negative_x: false

  #trajectory scoring parameters
  path_distance_bias: 32.0 
  goal_distance_bias: 24.0 
  occdist_scale: 0.01 
  forward_point_distance: 0.325
  stop_time_buffer: 0.2 
  scaling_speed: 0.25 
  max_scaling_factor: 0.2 

  #Oscillation prevention parameters
  oscillation_reset_dist: 0.05 
 
  #Global plan parameters
  prune_plan: true

  #Rotate recovery parameters (same as above but with different names)
  frequency: 20.0
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.2
