global_costmap:
  #Coordinate frame and tf parameters
  global_frame: /map
  robot_base_frame: base_footprint
  transform_tolerance: 0.2
  
  #Rate parameters
  update_frequency: 10
  publish_frequency: 10
  
  #Map management parameters
  static_map: true
  rolling_window: false
  width: 10
  height: 10
  resolution: 0.05
  origin_x: 0.0
  origin_y: 0.0
