local_costmap:
   global_frame: /map
   robot_base_frame: base_footprint
   update_frequency: 10.0
   publish_frequency: 10.0
   static_map: true
   rolling_window: false
   width: 4.0
   height: 4.0
   resolution: 0.05
   transform_tolerance: 0.5
