local_costmap:
  #Coordinate frame and tf parameters
  global_frame: /odom
  robot_base_frame: base_footprint
  transform_tolerance: 0.2

  #Rate parameters
  update_frequency: 10.0
  publish_frequency: 10.0

  #Map management parameters
  static_map: false
  rolling_window: true
    width: 4.0
    height: 4.0
    resolution: 0.05
    origin_x: 0.0
    origin_y: 0.0
