frequency: 25
sensor_timeout: 2
two_d_mode: true
world_frame: odom
odom_frame: odom
base_link_frame: base_footprint
odom0: /omni_odom
imu0: /imu/data
odom0_config: [false, false, false, 
               false, false, false,
               true,  true,  false,
               false, false, true]
imu0_config:  [false, false, false, 
               false, false, false,
               true,  true,  false,
               false, false, true,
               true,  true,  false]
odom0_differential: false
imu0_differential: true
imu0_remove_gravitational_acceleration: false
